package indy;

public class Constants {

    public static final double BIOME_SQUARE_SIZE = 60;
    public static final int BOARD_LENGTH = 40;
    public static final int FARM_INCOME = 3;
    public static final Tile[][] CANADA_MAP = // 5 x 20 custom map, Southern Canada
            {
                    {new Tile(new DeepWater(0,0)), new Tile(new ShallowWater(BIOME_SQUARE_SIZE, 0)), new Tile(new Forest(2 * BIOME_SQUARE_SIZE, 0)), new Tile(new Forest(3 * BIOME_SQUARE_SIZE, 0)), new Tile(new Mountain(4 * BIOME_SQUARE_SIZE, 0)),
                            new Tile(new Forest(5 * BIOME_SQUARE_SIZE, 0)), new Tile(new Plain(BIOME_SQUARE_SIZE * 6, 0)), new Tile(new Plain(BIOME_SQUARE_SIZE * 7, 0)), new Tile(new Plain(BIOME_SQUARE_SIZE * 8, 0)), new Tile(new Grassland(BIOME_SQUARE_SIZE * 9, 0)),
                            new Tile(new Forest(BIOME_SQUARE_SIZE * 10, 0)), new Tile(new Forest(BIOME_SQUARE_SIZE * 11, 0)), new Tile(new Forest(BIOME_SQUARE_SIZE * 12, 0)), new Tile(new Forest(BIOME_SQUARE_SIZE * 13, 0)), new Tile(new Forest(BIOME_SQUARE_SIZE * 14, 0)),
                            new Tile(new Grassland(BIOME_SQUARE_SIZE * 15, 0)), new Tile(new Grassland(BIOME_SQUARE_SIZE * 16, 0)), new Tile(new ShallowWater(BIOME_SQUARE_SIZE * 17, 0)), new Tile(new Grassland(BIOME_SQUARE_SIZE * 18, 0)), new Tile(new Forest(BIOME_SQUARE_SIZE * 19, 0))},
                    {new Tile(new DeepWater(0, BIOME_SQUARE_SIZE)), new Tile(new ShallowWater(1 * BIOME_SQUARE_SIZE, BIOME_SQUARE_SIZE)),new Tile(new ShallowWater(2 * BIOME_SQUARE_SIZE, BIOME_SQUARE_SIZE)),new Tile(new Forest(3 * BIOME_SQUARE_SIZE, BIOME_SQUARE_SIZE)),new Tile(new Mountain(4 * BIOME_SQUARE_SIZE, BIOME_SQUARE_SIZE)),
                            new Tile(new Mountain(5 * BIOME_SQUARE_SIZE, BIOME_SQUARE_SIZE)),new Tile(new Forest(6 * BIOME_SQUARE_SIZE, BIOME_SQUARE_SIZE)),new Tile(new Plain(7 * BIOME_SQUARE_SIZE, BIOME_SQUARE_SIZE)),new Tile(new Plain(8 * BIOME_SQUARE_SIZE, BIOME_SQUARE_SIZE)),new Tile(new Grassland(9 * BIOME_SQUARE_SIZE, BIOME_SQUARE_SIZE)),
                            new Tile(new Forest(10 * BIOME_SQUARE_SIZE, BIOME_SQUARE_SIZE)),new Tile(new Forest(11 * BIOME_SQUARE_SIZE, BIOME_SQUARE_SIZE)),new Tile(new Forest(12 * BIOME_SQUARE_SIZE, BIOME_SQUARE_SIZE)),new Tile(new Forest(13 * BIOME_SQUARE_SIZE, BIOME_SQUARE_SIZE)),new Tile(new Forest(14 * BIOME_SQUARE_SIZE, BIOME_SQUARE_SIZE)),
                            new Tile(new Grassland(15 * BIOME_SQUARE_SIZE, BIOME_SQUARE_SIZE)),new Tile(new Grassland(16 * BIOME_SQUARE_SIZE, BIOME_SQUARE_SIZE)),new Tile(new Grassland(17 * BIOME_SQUARE_SIZE, BIOME_SQUARE_SIZE)),new Tile(new Forest(18 * BIOME_SQUARE_SIZE, BIOME_SQUARE_SIZE)),new Tile(new Forest(19 * BIOME_SQUARE_SIZE, BIOME_SQUARE_SIZE))},
                    {new Tile(new DeepWater(0 * BIOME_SQUARE_SIZE, 2 * BIOME_SQUARE_SIZE)), new Tile(new ShallowWater(1 * BIOME_SQUARE_SIZE, 2 * BIOME_SQUARE_SIZE)),new Tile(new Grassland(2 * BIOME_SQUARE_SIZE, 2 * BIOME_SQUARE_SIZE)),new Tile(new Forest(3 * BIOME_SQUARE_SIZE, 2 * BIOME_SQUARE_SIZE)),new Tile(new Mountain(4 * BIOME_SQUARE_SIZE, 2 * BIOME_SQUARE_SIZE)),
                            new Tile(new Mountain(5 * BIOME_SQUARE_SIZE, 2 * BIOME_SQUARE_SIZE)),new Tile(new Forest(6 * BIOME_SQUARE_SIZE, 2 * BIOME_SQUARE_SIZE)),new Tile(new Plain(7 * BIOME_SQUARE_SIZE, 2 * BIOME_SQUARE_SIZE)),new Tile(new Plain(8 * BIOME_SQUARE_SIZE, 2 * BIOME_SQUARE_SIZE)),new Tile(new Plain(9 * BIOME_SQUARE_SIZE, 2 * BIOME_SQUARE_SIZE)),
                            new Tile(new Grassland(10 * BIOME_SQUARE_SIZE, 2 * BIOME_SQUARE_SIZE)),new Tile(new Forest(11 * BIOME_SQUARE_SIZE, 2 * BIOME_SQUARE_SIZE)),new Tile(new ShallowWater(12 * BIOME_SQUARE_SIZE, 2 * BIOME_SQUARE_SIZE)),new Tile(new Grassland(13 * BIOME_SQUARE_SIZE, 2 * BIOME_SQUARE_SIZE)),new Tile(new Grassland(14 * BIOME_SQUARE_SIZE, 2 * BIOME_SQUARE_SIZE)),
                            new Tile(new Grassland(15 * BIOME_SQUARE_SIZE, 2 * BIOME_SQUARE_SIZE)),new Tile(new Hill(16 * BIOME_SQUARE_SIZE, 2 * BIOME_SQUARE_SIZE)),new Tile(new Hill(17 * BIOME_SQUARE_SIZE, 2 * BIOME_SQUARE_SIZE)),new Tile(new Forest(18 * BIOME_SQUARE_SIZE, 2 * BIOME_SQUARE_SIZE)),new Tile(new ShallowWater(19 * BIOME_SQUARE_SIZE, 2 * BIOME_SQUARE_SIZE))},
                    {new Tile(new DeepWater(0 * BIOME_SQUARE_SIZE, 3 * BIOME_SQUARE_SIZE)), new Tile(new ShallowWater(1 * BIOME_SQUARE_SIZE, 3 * BIOME_SQUARE_SIZE)),new Tile(new Grassland(2 * BIOME_SQUARE_SIZE, 3 * BIOME_SQUARE_SIZE)),new Tile(new Plain(3 * BIOME_SQUARE_SIZE, 3 * BIOME_SQUARE_SIZE)),new Tile(new Plain(0 * BIOME_SQUARE_SIZE, 4 * BIOME_SQUARE_SIZE)),
                            new Tile(new Mountain(5 * BIOME_SQUARE_SIZE, 3 * BIOME_SQUARE_SIZE)),new Tile(new Mountain(6 * BIOME_SQUARE_SIZE, 3 * BIOME_SQUARE_SIZE)),new Tile(new Plain(7 * BIOME_SQUARE_SIZE, 3 * BIOME_SQUARE_SIZE)),new Tile(new Plain(8 * BIOME_SQUARE_SIZE, 3 * BIOME_SQUARE_SIZE)),new Tile(new Plain(9 * BIOME_SQUARE_SIZE, 3 * BIOME_SQUARE_SIZE)),
                            new Tile(new Grassland(10 * BIOME_SQUARE_SIZE, 3 * BIOME_SQUARE_SIZE)),new Tile(new Forest(11 * BIOME_SQUARE_SIZE, 3 * BIOME_SQUARE_SIZE)),new Tile(new Forest(12 * BIOME_SQUARE_SIZE, 3 * BIOME_SQUARE_SIZE)),new Tile(new ShallowWater(13 * BIOME_SQUARE_SIZE, 3 * BIOME_SQUARE_SIZE)),new Tile(new Grassland(14 * BIOME_SQUARE_SIZE, 3 * BIOME_SQUARE_SIZE)),
                            new Tile(new ShallowWater(15 * BIOME_SQUARE_SIZE, 3 * BIOME_SQUARE_SIZE)),new Tile(new Hill(16 * BIOME_SQUARE_SIZE, 3 * BIOME_SQUARE_SIZE)),new Tile(new Forest(17 * BIOME_SQUARE_SIZE, 3 * BIOME_SQUARE_SIZE)),new Tile(new Grassland(18 * BIOME_SQUARE_SIZE, 3 * BIOME_SQUARE_SIZE)),new Tile(new ShallowWater(19 * BIOME_SQUARE_SIZE, 3 * BIOME_SQUARE_SIZE))},
                    {new Tile(new DeepWater(0 * BIOME_SQUARE_SIZE, 4 * BIOME_SQUARE_SIZE)), new Tile(new ShallowWater(1 * BIOME_SQUARE_SIZE, 4 * BIOME_SQUARE_SIZE)),new Tile(new Forest(2 * BIOME_SQUARE_SIZE, 4 * BIOME_SQUARE_SIZE)),new Tile(new Plain(3 * BIOME_SQUARE_SIZE, 4 * BIOME_SQUARE_SIZE)),new Tile(new Plain(4 * BIOME_SQUARE_SIZE, 4 * BIOME_SQUARE_SIZE)),
                            new Tile(new Mountain(5 * BIOME_SQUARE_SIZE, 4 * BIOME_SQUARE_SIZE)),new Tile(new Mountain(6 * BIOME_SQUARE_SIZE, 4 * BIOME_SQUARE_SIZE)),new Tile(new Hill(7 * BIOME_SQUARE_SIZE, 4 * BIOME_SQUARE_SIZE)),new Tile(new Plain(8 * BIOME_SQUARE_SIZE, 4 * BIOME_SQUARE_SIZE)),new Tile(new Grassland(9 * BIOME_SQUARE_SIZE, 4 * BIOME_SQUARE_SIZE)),
                            new Tile(new Forest(10 * BIOME_SQUARE_SIZE, 4 * BIOME_SQUARE_SIZE)),new Tile(new Grassland(11 * BIOME_SQUARE_SIZE, 4 * BIOME_SQUARE_SIZE)),new Tile(new ShallowWater(12 * BIOME_SQUARE_SIZE, 4 * BIOME_SQUARE_SIZE)),new Tile(new Forest(13 * BIOME_SQUARE_SIZE, 4 * BIOME_SQUARE_SIZE)),new Tile(new ShallowWater(14 * BIOME_SQUARE_SIZE, 4 * BIOME_SQUARE_SIZE)),
                            new Tile(new Grassland(15 * BIOME_SQUARE_SIZE, 4 * BIOME_SQUARE_SIZE)),new Tile(new Mountain(16 * BIOME_SQUARE_SIZE, 4 * BIOME_SQUARE_SIZE)),new Tile(new Grassland(17 * BIOME_SQUARE_SIZE, 4 * BIOME_SQUARE_SIZE)),new Tile(new Grassland(18 * BIOME_SQUARE_SIZE, 4 * BIOME_SQUARE_SIZE)),new Tile(new ShallowWater(19 * BIOME_SQUARE_SIZE, 4 * BIOME_SQUARE_SIZE))
                    }
            };
}
